### ISSUE TITLE
一个小请求

### ISSUE THREAD

**Issue by Neverland7-7** [sowicm/24points#1]
您好，我正在学习这个代码。但我不知道怎么将这个小游戏在Visual Studio 2022 上运行，或许有.sln之类的文件吗。希望您能帮助

**Comment by zhangriyueming** [comment]
> 您好，我正在学习这个代码。但我不知道怎么将这个小游戏在Visual Studio 2022 上运行，或许有.sln之类的文件吗。希望您能帮助

你可以用 Visual Studio 2022 新建一个工程然后把这些文件添加进去
